### ISSUE TITLE
集成一致性分位数回归参数设置问题

### ISSUE THREAD

**Issue by LLii358** [FilippoMB/Ensemble-Conformalized-Quantile-Regression#3]
我想问一下集成一致性分位数回归代码里，time_steps_in=24,time_steps_out=6这里。如果数据是每分钟一条，这里该如何表示呢。

**Comment by FilippoMB** [comment]
Not sure if I got your question right as it is partially written in Chinese, which I do not understand.

You asked what to do if you have a minute resolution rather than an hourly resolution. If you still want to predict six hours ahead using the past 24 hours, like in the example code, you have to multiply these windows by 60, e.g., time_steps_in=24*60 and time_steps_out=6*60.

**Comment by LLii358** [comment]
Thanks a lot. But here are some question from me that I wanna talk about with you，could you leave your contact information for me ? Please....

**Comment by FilippoMB** [comment]
Hi, you can find my contact information here: https://sites.google.com/view/filippombianchi/home
