### ISSUE TITLE
About the outcome of the prediction

### ISSUE THREAD

**Issue by xianxiaogao** [FilippoMB/Ensemble-Conformalized-Quantile-Regression#4]
Hello, thank you for sharing the code！
However, in the process of learning, I had the following problems: After training the network with the verification set, I predicted the test set, and found that the test set predicted the same result every day. What is the cause of this problem?
![image](https://user-images.githubusercontent.com/118738753/218296621-7cc915e5-9fa8-4e97-9d82-e7e9da428e73.png)
Looking forward to your reply！

**Comment by LLii358** [comment]
Hello guys， I am very glad to see someone else talking about this code，here are some question from me that I wanna talk about with you，could you leave your contact information for me ?

**Comment by LLii358** [comment]
Thanks a lot !

**Comment by xianxiaogao** [comment]
Glad to receive your reply. Here is my email: 2725909475@qq.com

**Comment by FilippoMB** [comment]
Hi! Here are a couple of comments from the top of my head:
- are you sure the predictions are *exactly* the same every day? Maybe you can create slices, one for each day, and compute the difference among them numerically to see if they are really identical.
- it seems that every day there is a very similar pattern, except for some fluctuations that seem (at first glance) rather noisy-like. If that's the case, since noise cannot be modelled by definition, I would not be surprised that the best thing the LSTM can do is to return the same pattern every day.
- Following up on the previous point, you might want to analyze more your time series. For example, you could remove the main seasonality by doing a seasonal differentiation. The residual signal you get is noise-like? It could be a good idea to give this residual as the input to the model to see if there is some information it can get out of it or if it just ends up predicting a straight line.
- Try also the other models, for example, the TCN or (even better) something more powerful besides the baseline you find in this repo. The purpose of this repo is not to provide particularly powerful models for time series forecasting, but rather to give a working implementation of the conformalized quantile regression. If you have to tackle a real-world task I suggest you try more powerful models and then put the conformalized QR on top of those.

I hope this helps!

**Comment by xianxiaogao** [comment]
Thanks for your reply! I also made some modifications according to your prompt. Before, because the output step length was too long, the predicted results were very similar.

However, there is also a heart problem that bothers me. Although the fitting effect of the median is good, why do the predicted results fluctuate frequently? What might be the causes?
![4069c3978685e187cfd9a1f364a0121](https://user-images.githubusercontent.com/118738753/219945658-1f151e9d-0464-4c94-9d79-10cf37ae3105.png)
In addition, the prediction effect of TCN is not so ideal, which is due to the model is not well trained or the parameter setting.
![2765a7a7d2ace067aed0b9462bfba73](https://user-images.githubusercontent.com/118738753/219945722-d3dc589d-908f-4004-b4fb-ba2146ef8a7b.png)
Looking forward to your reply and thanks again for sharing the code.

**Comment by FilippoMB** [comment]
Hi, sorry for the late reply.
Did you manage to solve the issue? It's very strange what you are getting there and I wonder if there is something off with how the data batches are prepared.

I suggest trying to fit the LSTM or TCN model **without** doing conformalized QR in order to see if everything is OK. For example, you can predict only the most likely value and optimize the MSE or, if you want to modify the code as little as possible, you can predict the 0.5 quantile and keep optimizing the pinball loss.

**Comment by xianxiaogao** [comment]
Thank you for your reply. 
My problem has been solved. The advice you gave was excellent. My work still carried out interval prediction based on your model, adopted the model of CNN-BiGRU, and divided the prediction results by listening to your advice.
![image](https://user-images.githubusercontent.com/118738753/224990220-e45fb4af-f134-47d5-9b1e-e528fe4370be.png)
![image](https://user-images.githubusercontent.com/118738753/224990277-faa15f92-d907-4d71-a7a4-de651ce9a7bc.png)
Although it seems that the median fitting effect is not very good, I will further improve it in the follow-up work. This is basically the end of my questions. Thank you very much for the author's patient reply every time. Thank you, have a nice life!

**Comment by FilippoMB** [comment]
Happy to hear things worked out :)
The results you got there seem very reasonable: where the prediction is less precise, the uncertainty is higher (larger PI). This is exactly what one would expect.

Cheers!

**Comment by xianxiaogao** [comment]
Thanks to the authors for their patience every time.

Cheers!!!
